table date_angajati
	lineageTag: 3a4ec4e3-350b-485b-9ae5-aa3da26fb5c2

	measure Scor_Estimat = AVERAGE(date_angajati[Scor_Performanta]) + (SELECTEDVALUE('Simulare_Training'[Simulare_Training]) * 0.5)
		lineageTag: ba05a79a-3a5f-44d0-aa20-aa9c82606650

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Castig_Puncte = [Scor_Estimat] - AVERAGE(date_angajati[Scor_Performanta])
		lineageTag: 7d79913f-7b51-4cb4-ac5e-4f9873bfef10

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Prag_Burnout = 220
		formatString: 0
		lineageTag: 31b141ca-9329-4115-9bf0-dce88cad6ec1

	measure Total_Angajati = DISTINCTCOUNT('date_angajati'[ID_Angajat])
		formatString: 0
		lineageTag: d1fa68c7-c986-4973-b975-fdcdf5385639

	measure Procent_Risc =
			
			DIVIDE(
			    COUNTROWS(FILTER('date_angajati', 'date_angajati'[Status_Risc] = "Risc Ridicat")),
			    COUNTROWS('date_angajati')
			) * 100
		lineageTag: b51d803b-14a9-4eb4-8feb-c95f3bec2359

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Dept_Burnout =
			
			TOPN(
			    1,
			    VALUES('date_angajati'[Departament]),
			    CALCULATE(
			        COUNTROWS(FILTER('date_angajati', 'date_angajati'[Status_Risc] = "Risc Ridicat")),
			        ALLEXCEPT('date_angajati', 'date_angajati'[Departament])
			    )
			)
		lineageTag: 493aea2d-c9f8-4ddc-80a9-1d81f3c2feb7

	measure Top_Performers = COUNTROWS(FILTER('date_angajati', 'date_angajati'[Status_Risc] = "Potential"))
		formatString: 0
		lineageTag: ceeb238b-336c-45c1-a8c1-cf9b98d3b11c

	column ID_Angajat
		dataType: int64
		formatString: 0
		lineageTag: bec52b1f-b870-4313-8474-2c4506a157b7
		summarizeBy: sum
		sourceColumn: ID_Angajat

		annotation SummarizationSetBy = Automatic

	column Manager
		dataType: string
		lineageTag: 45a6d094-2975-443f-b3f1-f813a3fae06b
		summarizeBy: none
		sourceColumn: Manager

		annotation SummarizationSetBy = Automatic

	column Departament
		dataType: string
		lineageTag: a8bced27-53e5-41fb-acb1-ceeee38da931
		summarizeBy: none
		sourceColumn: Departament

		annotation SummarizationSetBy = Automatic

	column Senioritate
		dataType: string
		lineageTag: 230b4dd8-1ba1-4794-a121-b9ae885bf27a
		summarizeBy: none
		sourceColumn: Senioritate

		annotation SummarizationSetBy = Automatic

	column Ore_Lucrate
		dataType: int64
		lineageTag: e082e8fe-0cd6-4a51-b201-c7da5556ff79
		summarizeBy: sum
		sourceColumn: Ore_Lucrate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Proiecte_Finalizate
		dataType: double
		lineageTag: 1e380284-08a1-4aa7-bcaf-e23fa6a42b01
		summarizeBy: sum
		sourceColumn: Proiecte_Finalizate

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Feedback_Clienti
		dataType: double
		lineageTag: 0697c493-0314-44c7-a0d2-814ef5790ee3
		summarizeBy: sum
		sourceColumn: Feedback_Clienti

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Training_Ore
		dataType: double
		lineageTag: d86f4d59-1636-4bce-97ca-f870b1eebb3f
		summarizeBy: sum
		sourceColumn: Training_Ore

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Scor_Performanta
		dataType: double
		lineageTag: 4357e83f-4570-4ac6-8f64-30ece691cd76
		summarizeBy: sum
		sourceColumn: Scor_Performanta

		changedProperty = DataType

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Risc_Plecare_Scor
		dataType: double
		lineageTag: b9719039-9433-4193-a8b8-a00db294824b
		summarizeBy: sum
		sourceColumn: Risc_Plecare_Scor

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Status_Risc
		dataType: string
		lineageTag: 6f11dd93-1fa8-461b-bb03-949fab7c4e9e
		summarizeBy: none
		sourceColumn: Status_Risc

		annotation SummarizationSetBy = Automatic

	column Data
		dataType: dateTime
		formatString: mmmm yyyy
		lineageTag: 7af9051c-2a00-45cb-b38a-fb25b5dcd861
		summarizeBy: none
		sourceColumn: Data

		variation Variation
			isDefault
			relationship: 9f2bfaeb-89e1-4ee3-bf00-457d955b7443
			defaultHierarchy: LocalDateTable_9afced05-d176-4945-abe2-39443a15d015.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Oras
		dataType: string
		lineageTag: 92d0bd36-6aba-4f5d-b927-03c5032a8271
		summarizeBy: none
		sourceColumn: Oras

		annotation SummarizationSetBy = Automatic

	column Senioritate_Num
		dataType: int64
		formatString: 0
		lineageTag: e877408a-bcec-4476-bbee-851dd766674b
		summarizeBy: sum
		sourceColumn: Senioritate_Num

		annotation SummarizationSetBy = Automatic

	column Probabilitate_Risc_RF
		dataType: int64
		formatString: 0.00
		lineageTag: 1dd08811-de57-404a-a68a-49a5719ed292
		summarizeBy: sum
		sourceColumn: Probabilitate_Risc_RF

		annotation SummarizationSetBy = Automatic

	partition date_angajati = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Sonia\OneDrive\Desktop\licenta\date_angajati_istoric.csv"),[Delimiter=",", Columns=13, Encoding=1250, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Run Python script" = Python.Execute("import pandas as pd#(lf)from sklearn.ensemble import RandomForestClassifier#(lf)#(lf)# 'dataset' este tabelul tău din Power BI#(lf)df = dataset#(lf)#(lf)# Mapăm Senioritatea în numere pentru ca algoritmul să poată face calcule#(lf)# Junior = 1, Mid = 2, Senior = 3#(lf)senioritate_map = {'Junior': 1, 'Mid': 2, 'Senior': 3}#(lf)df['Senioritate_Num'] = df['Senioritate'].map(senioritate_map)#(lf)#(lf)# Alegem variabilele de intrare care EXISTĂ în codul tău de generare#(lf)# Folosim: Ore_Lucrate, Proiecte_Finalizate, Feedback_Clienti și Senioritate_Num#(lf)X = df[['Ore_Lucrate', 'Proiecte_Finalizate', 'Feedback_Clienti', 'Senioritate_Num']]#(lf)#(lf)# Cream o coloană binară pentru antrenare (1 dacă e Risc Ridicat, 0 în rest)#(lf)y = (df['Status_Risc'] == 'Risc Ridicat').astype(int)#(lf)#(lf)# Antrenăm modelul Random Forest#(lf)model = RandomForestClassifier(n_estimators=100, random_state=101)#(lf)model.fit(X, y)#(lf)#(lf)# Generăm scorul de risc (probabilitatea între 0 și 1)#(lf)df['Probabilitate_Risc_RF'] = model.predict_proba(X)[:, 1]#(lf)#(lf)output = df",[dataset=#"Promoted Headers"]),
				    output = #"Run Python script"{[Name="output"]}[Value],
				    #"Changed Type" = Table.TransformColumnTypes(output,{{"ID_Angajat", Int64.Type}, {"Manager", type text}, {"Departament", type text}, {"Senioritate", type text}, {"Oras", type text}, {"Data", type date}, {"Ore_Lucrate", Int64.Type}, {"Proiecte_Finalizate", Int64.Type}, {"Feedback_Clienti", Int64.Type}, {"Training_Ore", Int64.Type}, {"Scor_Performanta", Int64.Type}, {"Risc_Plecare_Scor", Int64.Type}, {"Status_Risc", type text}, {"Senioritate_Num", Int64.Type}, {"Probabilitate_Risc_RF", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

